name = "ClimFluids"
uuid = "68475963-a72f-47d4-b871-9c5545ecd1c0"
authors = ["The ClimFlows contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
