name = "ClimFluids"
uuid = "68475963-a72f-47d4-b871-9c5545ecd1c0"
authors = ["The ClimFlows contributors"]
version = "1.0.0-DEV"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"

[compat]
MuladdMacro = "0.2"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
